### ISSUE TITLE
Feature request: App Notification

### ISSUE THREAD

**Issue by GOchispaGO** [traccar/traccar-manager-android#41]
We now have notifications sent via EMAIL and via WEB.
Could you add a third column to notify via APP ?
(TManagerAlert icon appears in the top notification bar of our Android device)
THANKS

**Comment by tananaev** [comment]
There is no plan for it at the moment, but it's something we can consider in future. My only problem is that it would require integration with proprietary Apple and Google services.

**Comment by jon-stumpf** [comment]
Moved my feature request from [Traccar Web](https://github.com/tananaev/traccar-web), Issue [548](https://github.com/tananaev/traccar-web/issues/548) to here.  Since it duplicated this issue in this repository, I am continuing the conversation here.

Mobile applications are not my forte but I am interested in learning to implement.  Can you direct me?  Simple technical terms or APIs that I can start my search would be appreciated.

\- jss

**Comment by tananaev** [comment]
If you want to use push notifications you can look into using Firebase. It's available for both Android and iOS.

If you are after regular notifications, then there is simple API for each platform that you can use.

**Comment by jensMF** [comment]
Would it be possible to support unified push? https://unifiedpush.org/

**Comment by tananaev** [comment]
We already support push notifications.
